spring:
  application:
    name: ratelimiter

  data:
    redis:
      connect-timeout: 500ms
      timeout: 200ms

      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 200ms

      cluster:
        nodes:
          - redis-0.redis:6379
          - redis-1.redis:6379
          - redis-2.redis:6379
          - redis-3.redis:6379
          - redis-4.redis:6379
          - redis-5.redis:6379

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: products
              uri: http://product-service:7070
              predicates:
                - Path=/products,/products/**
              filters:
                - RateLimit

server:
  port: 8080

zookeeper:
  connect-string: ${ZOOKEEPER_HOST}:2181

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    gateway:
      access: read-only